### ISSUE TITLE
Tests fail with rc3

### ISSUE THREAD

**Issue by xMrWhite** [michaelbromley/ng2-pagination#56] opened 2016-07-05 19:54 UTC
**Angular 2 version**:
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "0.1.1",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.3",
**ng2-pagination version**:
 master
**Description of issue**:
 passes 35/50 2 skipped
**Steps to reproduce**:
 bump angular to rc3, npm install, typings isntall, npm run test

Any relevant code:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 35 of 50 (skipped 2) SUCCESS (0 secs / 1.308 secs)
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 35 of 50 (skipped 2) DISCONNECTED (11.333 secs / 1.308 secs)
```

**Comment by xMrWhite** [comment] 2016-07-05 19:56
I'm happy to make a pull request, but I'm not familiar with karma, so I'm not sure where to find test 36 and how to run a detailed stack trace for that error.

**Comment by michaelbromley** [comment] 2016-07-05 20:46
Hi,

Thanks for the report. I'll probably be updating an app I'm working on to rc.4 later this week, in which case I'll take the opportunity to update this project too.

**Comment by michaelbromley** [comment] 2016-07-08 15:57
Just discovered the cause of this - it was because in rc.3+, some tests fail, and Jasmine tries to pretty-print the JavaScript object which is failing. It tries to recursively walk an Angular DebugElement which contains circular references, thus gets into an infinite loop and the browser dies.

The solution is to use 

```
jasmine.MAX_PRETTY_PRINT_DEPTH = 3;
```

and then if a test fails, the browser does not die. So now I just need to fix the broken tests....

**Comment by michaelbromley** [comment] 2016-07-14 10:22
Fixed with the latest version v.0.3.5

**Closed by michaelbromley** 2016-07-14 10:22 UTC
