### ISSUE TITLE
Update Content on Collection array change

### ISSUE THREAD

**Issue by RicardoVaranda** [michaelbromley/ng2-pagination#59] opened 2016-07-19 13:40 UTC
Hey guys, 
is it possible to update the content of the current page after the content of the array is changed, for some reason it changes the contents after I change page and come back so there seems to be a detection change within the onPageChange listener just wondering if there is any way we can call this to update it on content change.

**Comment by michaelbromley** [comment] 2016-07-21 07:26
Hi,

This should work as you describe without needing to switch pages back and forth. Can you reproduce the issue in a plunk? You can use this as a starter: http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview

**Comment by RicardoVaranda** [comment] 2016-07-21 13:17
Hi Michael I fixed it by manually calling: 
        _changeDetectorRef.detectChanges();

**Comment by michaelbromley** [comment] 2016-07-21 13:28
Okay, but that is strange - you shouldn't need to do that. Here is a demo that demonstrates that it should be possible to update an object in the collection, or even replace an object, and the pagination will update: http://plnkr.co/edit/6h3cgOovYbv7XD1DPgKg?p=preview

**Comment by RicardoVaranda** [comment] 2016-07-22 11:04
The issue I have is that I am editing the content of existing items in the collections array for example,

```
var collections= ['a','b','c','d'];

collections[0] = 'I Changed!';
```

If I run that it won't update it visually until you call change detector. On yours it works since you did it via clicking a button which actually triggers the change detector in angular but try and do it using something like this,

```
$('#my_input').on('change', function(){
  collections[0] = $('#my_input').val();
});
```

Since this is activated programmatically it doesn't seem to activate the change detector:
http://plnkr.co/edit/m5fS7WH0OvenIZdGPMzG?p=preview

Check that out, the content will only change once you switch pages.

**Comment by michaelbromley** [comment] 2016-07-22 11:30
I see - thanks for the demo. I get why this is happening now, and this is an interesting issue! It seems that this is just the expected behaviour of Angular in this case. [This issue seems to be related](https://github.com/angular/angular/issues/7792). 

From what I can tell, the problem is that the event listener in your example is not running within the Angular "Zone", which is why the change detection is not being invoked on each event. Following from this, another way to solve it is like this:

```TypeScript
constructor(private ngZone: NgZone) {}

ngOnInit() {
  this.ngZone.run(() => {
    // code which mutates the collection...
  });
}
```

I'll close this now since it is not directly to do with this module.

**Closed by michaelbromley** 2016-07-22 11:30 UTC

**Comment by RicardoVaranda** [comment] 2016-07-22 12:03
Thanks for the ngZone alternative, I'll use it in the future.
